image: node:8
pipelines:
  default:
    - step:
        script:
          - npm install
          - npm run build
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t rmachnik/rebridge-frontend .
          - docker push rmachnik/rebridge-frontend:latest
